theme = "nord"

[editor]
line-number = "relative"
mouse = false
shell = ["zsh", "-c"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.whitespace.render]
nbsp = "all"
tab = "all"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false
