[language-server.vscode-json-language-server.config]
"provideFormatter" = true
"json" = { "keepLines" = { "enable" = true } }

[language-server.godot]
command = "ncat"
args = ["127.0.0.1", "6005"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "markdown"
soft-wrap.enable = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "c-sharp"
auto-format = true

[[language]]
name = "python"
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true

[[language]]
name = "gdscript"
language-servers = ["godot"]
