[[language]]
name = "gdscript"
language-server = { command = "nc", args = ["localhost", "6005"], language-id = "gdscript" }
formatter = { command = "gdformat", args = ["-"] }
auto-format = true

[[language]]
name = "c-sharp"
language-server = { command = "mono", args = [ "/home/iver/omnisharp-linux-x64/omnisharp/OmniSharp.exe", "--languageserver" ] }
auto-format = true
