## SYNTAX HIGHLIGHTING

# Constants
"constant" = "hack6"
"constant.builtin" = "hack10"
"constant.builtin.boolean" = "hack10"
"constant.builtin.character" = "purple"
"constant.character.escape" = "yellow"
"constant.macro" = "hack10"
"constant.numeric" = "purple"
"constructor" = "hack8"

# Diagnostics
"diagnostic" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"error" = "red"
"diagnostic.hint" = { underline = { color = "hack3", style = "curl" } }
"hint" = "hack3"
"diagnostic.info" = { underline = { color = "hack5", style = "curl" } }
"info" = "hack5"
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"warning" = "yellow"
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# Diffs
"diff.delta" = "yellow"
"diff.minus" = "red"
"diff.plus" = "green"

# Functions
"function" = "hack7"
"function.builtin" = "hack6"
"function.method" = "hack7"
"function.macro" = "hack9"
"function.special" = "hack9"

# Git
"git.delta.moved" = "orange"

# Keywords
"keyword" = "hack9"
"keyword.control.conditional" = "hack9"
"keyword.control.exception" = "hack9"
"keyword.control.repeat" = "hack9"
"keyword.directive" = "hack9"
"keyword.function" = "hack9"
"keyword.operator" = "hack9"
"keyword.return" = "hack9"
"keyword.storage.modifier" = "hack9"
"keyword.storage.type" = "hack9"

# Punctuation
"punctuation" = "hack8"
"punctuation.bracket" = "hack8"
"punctuation.delimiter" = "hack8"
"punctuation.special" = "hack8"

# Strings
"string" = "green"
"string.escape" = "yellow"
"string.regex" = "yellow"
"string.special" = "yellow"

# Types
"type" = "hack7"
"type.builtin" = "hack7"

# Variables
"variable" = "hack7"
"variable.builtin" = "hack10"
"variable.other.member" = "hack7"
"variable.parameter" = "hack9"
"attribute" = "hack10"

# Misc.
"label" = "hack6"
"namespace" = "hack3"
"operator" = "hack10"
"special" = "hack9"
"tag" = "hack10"
"comment" = { fg = "hack3", modifiers = ["italic"] }

## EDITOR UI COLORS

"ui.background" = { bg = "hack0" }
"ui.text" = "hack2"
"ui.window" = "hack1"

# Debug
"ui.debug.active" = "yellow"
"ui.debug.breakpoint" = "red"

# Popus and menus
"ui.menu" = { bg = "hack0" }
"ui.menu.scroll" = { fg = "hack2", bg = "hack1" }
"ui.menu.selected" = { fg = "hack10", bg = "hack1" }
"ui.popup" = { bg = "hack1" }
"ui.popup.info" = { bg = "hack1" }
"ui.help" = { bg = "hack1" }
"ui.text.focus" = { fg = "hack10", bg = "hack1" }

# Gutter
"ui.gutter" = "hack2"
"ui.linenr" = "hack1"
"ui.linenr.selected" = "hack2"

# Cursor
"ui.cursor.primary" = { fg = "hack0", bg = "hack10" }
"ui.cursorcolumn.primary" = { bg = "hack1" }
"ui.cursorline.primary" = { bg = "hack1" }

"ui.selection" = { fg = "hack9", bg = "hack1" }
"ui.highlight" = { fg = "hack5", bg = "hack1" }

# Statusline
"ui.statusline" = {  bg = "hack0" }
"ui.statusline.inactive" = { fg = "hack10", bg = "hack1" }
"ui.statusline.insert" = { fg = "hack1", bg = "hack2" }
"ui.statusline.normal" = { fg = "hack1", bg = "hack5" }
"ui.statusline.select" = { fg = "hack1", bg = "hack6" }
"ui.statusline.separator" = "hack1"

# Virtual/invisible text
"ui.virtual.indent-guide" = "hack1"
"ui.virtual.inlay-hint" = { fg = "hack1", modifiers = ["italic"] }
"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "hack1" }
"ui.virtual.whitespace" = "hack1"
"ui.virtual.wrap" = "hack1"

# Bufferline
"ui.bufferline" = { fg = "hack2", bg = "hack1" }
"ui.bufferline.active" = { fg = "hack2", bg = "hack1", underline = { color = "hack5", style = "line" }, modifiers = [ "italic" ] }

# Markup
"markup.heading" = "hack5"
"markup.list" = "hack4"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.text" = "hack5"
"markup.raw" = "hack6"

[palette]
hack0 = "#01161b"
hack1 = "#022a34"
hack2 = "#a3b5b8"

hack3 = "#007b82"
hack4 = "#028c94"
hack5 = "#039ca4"
hack6 = "#04acb5"
hack7 = "#05bbc5"
hack8 = "#00cccc"
hack9 = "#06ccd7"
hack10 = "#66ffff"

red = "#bf616a"
orange = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
purple = "#b48ead"
