inherits = "rose_pine"

# make the cursor white
"ui.cursor" = { fg = "pine", bg = "text" }
"ui.cursor.primary" = { fg = "pine", bg = "text" }

# make the background transparent for acrylic
"ui.background" = {}
